### ISSUE TITLE
New git tag for v6

### ISSUE THREAD

**Issue by justwheel** [multiplexd/brightlight#5]
I noticed v6 was a big rewrite and I'd like to update the Fedora package. Could you add a new git tag for v6 so [release-monitoring.org](https://release-monitoring.org/project/16296/) will pick it up? It will also simplify the RPM spec file.

**Comment by multiplexd** [comment]
It seems I forgot to push the tags for the v6 release. I've just tagged v7, as there was a minor bug in the `getopt_long()` handling, so you can jump straight to that version.

**Comment by justwheel** [comment]
Thanks. I'll work on getting the package updated. :+1:

**Comment by justwheel** [comment]
A [new package update for v7](https://bodhi.fedoraproject.org/updates/?packages=brightlight) will soon be available for Fedora 27, 28, and 29.
