### ISSUE TITLE
ubuntu 20.04 installation

### ISSUE THREAD

**Issue by LambLeeg** [multiplexd/brightlight#9]
So, I did ` git clone https://github.com/multiplexd/brightlight.git` and make but I have an issue to install it. 
![20200621_12h47m57s_grim](https://user-images.githubusercontent.com/59935189/85221589-79b02800-b3bd-11ea-8377-5530179f4115.png)

**Comment by multiplexd** [comment]
Hi there! I've managed to reproduce the issue you appear to be having, and it looks like you don't have the `libbsd-dev` package installed. Can you try installing that package (using `sudo apt-get install libbsd-dev`) and then see if the build works correctly?

**Comment by LambLeeg** [comment]
Well, I have installed it but still error
![20200621_19h57m36s_grim](https://user-images.githubusercontent.com/59935189/85230534-881c3500-b3f9-11ea-93ed-8945d2d61886.png)

**Comment by multiplexd** [comment]
Hmm, I don't think I can immediately see what the issue is here. If the build has worked correctly, there should be a `brightlight` executable file in the project directory, which should should be able to run as `./brightlight`. If you can run `./brightlight -v` and get the following output:
```
brightlight, v8
Copyright (C) 2016, 2017, 2018, 2019 multiplexd <multi@in-addr.xyz>

This is free software, licenced under an ISC-like licence. You are
free to use, redistribute and modify this software as you wish, but
there is NO WARRANTY.
```
then the build has worked correctly.

**Comment by LambLeeg** [comment]
This command has the following output:
`bash: ./brightlight: Is a directory`

**Comment by multiplexd** [comment]
Hmm, are you running that from within the project directory? My expectation is that the following sequence of commands, run in an empty directory, should work correctly:
```
git clone https://github.com/multiplexd/brightlight
cd brightlight
make
./brightlight -v
```
Can you double check this, just to be sure?

**Comment by LambLeeg** [comment]
I tried it again, still, nothing changed.

**Comment by multiplexd** [comment]
> This command has the following output:
> `bash: ./brightlight: Is a directory`

This error message means that there is a directory with the name `brightlight` in your current working directory. Can you double check that you're definitely inside the project directory, and that running `make` creates an executable file called "brightlight"?

I've managed to build and run brightlight successfully on an Ubuntu 20.04 machine of my own, so I'm not sure what's causing the issues you're seeing.
